package com.example.instrumentation

/**
 * REPL script (change values as needed):
 * ```kotlin
private val alphabet = ('a'..'z').toList()
private val random = Random(1587309672444L)

fun randomString(length: Int) =
    String(CharArray(length) { alphabet[random.nextInt(alphabet.size)] })

fun printObject(map: Map<String, String>) {
    println("object {")
    map.forEach { (key, value) ->
        println("  val $key: String = \"$value\"")
    }
    println("}")
}

fun printMap(map: Map<String, String>) {
    println("LinkedHashMap<String, String>().also {")
    map.forEach { (key, value) ->
        println("  it[\"$key\"] = \"$value\"")
    }
    println("}")
}

val map = mutableMapOf<String, String>().apply {
    repeat(128) {
        put(randomString(4), randomString(32))
    }
}

printObject(map)
printMap(map)
 * ```
 */
fun printObjectVsMap() {
    printObjectVsMap1()
    println()
    LinkedHashMap<Int, String>().also { map ->
        repeat(1024) {
            map[it] = ""
        }
    }
}

fun printObjectVsMap1() {
    val any = object {
        val ioqr: String = "wfnjuuzvtwpaiobztthgnusiezqebthi"
        val ucpa: String = "fvvzuupgypdwhabsdibxnkenpgefkeon"
        val zdxr: String = "ioqvkrrdrzdzxcteabhyaoejcvsckmsy"
        val stmw: String = "okkuaaekibtmmjrprxltfzusbagyvtcd"
        val mreb: String = "edavfspocapwrialvwnwcupwwcbiwlwt"
        val objg: String = "guudtkspctpyiihzukinhifmhhxzokgu"
        val muxx: String = "ecurtjsoiaobqxudvsethwzgbratwsis"
        val ewzl: String = "ukxypolxoyndraiaxsatjtrtuznvurmb"
        val mcyx: String = "ickiswtumkidcufofbrzqhjgqammnorn"
        val foqi: String = "aqosuqpectvqfebxewvbzathwoltwkuj"
        val ukak: String = "lgzlwiiyductkujorqbxztnggnjsslbz"
        val slem: String = "dedcuygbwbywbskmshjhqdbssgqjzgbq"
        val lrhj: String = "tcvcooeeorlkhhvqvqqmseatqbeygaeg"
        val nwag: String = "mdlfzjlhqsxadqediseebxzaoiedbcfp"
        val eftz: String = "ykeyrupitbjktqahaeaeziwxxbogpnuv"
        val wwsc: String = "wktikamkuvasgxjqfhzddvqpmfciabey"
        val zrex: String = "rxhbzomshcqiolltmbsuroquhmgamacw"
        val maxb: String = "tubunywflprabuswbaxwqxmrdgqtvbwh"
        val wiqy: String = "pkxzlutxzvshexadsuiopfzbhcwfqwiz"
        val buhz: String = "ghawalybgitzetwvsgfzltweobxocged"
        val zrlg: String = "zajxousbleadbnlbertocztlexvloxiu"
        val yben: String = "udikcoefoseyjmpdzcqropltquousobt"
        val jvis: String = "ezymshefayujluyhosuhnuzlnhvutcyw"
        val gbsg: String = "xilzjkvkanrpbsnpmozqcmscuiifjyil"
        val aeyv: String = "vpmomqciqzavrvfqmayvifnrycuwuhed"
        val jrbt: String = "xbzvsfluotejwnqmlaovzldnvchlexnu"
        val jrdn: String = "wfvnhxstpnyjvtlmxevofgziwdjcsdny"
        val ddeh: String = "utsyiimeldbioxaauhztcdlblxvhyyfp"
        val jljt: String = "wazlrafinmbxieapypltwmipcvqdgrjk"
        val easb: String = "gwxbugljpjaeegynaqmqwpplxxnvzfhk"
        val olna: String = "qesufdkzlocalhzhlkthymlhitggxhck"
        val iqky: String = "vajtxhjkbjbrwupknijlcheoqqltftru"
        val iwxi: String = "sdeqpqcqdzdjgkjujacoztsrkvwjkezb"
        val fkan: String = "nxqlplzzwrttiwuaplohiucxsidfznnu"
        val menh: String = "somabofuzswvfuvskbhafcllryvdzgjc"
        val tyia: String = "qaayltmxtgwdvqjcfnrpohpwmqspczcb"
        val fvdm: String = "azrsdachaejjhuxlaknthhvxqyaehsyu"
        val zicj: String = "nevamciuhnjcxdepksggzjknoymudqjq"
        val gxmb: String = "iuazruescaeedrqzlibyryizxrcnpmtm"
        val emfu: String = "dzhjntpwyhlprkuibdxnimkwhryidbtc"
        val vbub: String = "ybumflwygzxjmtwcrldanhgqpljjjpnt"
        val yisg: String = "giyhtdilyneqnmjdlwawvkagllgefazu"
        val rtnd: String = "xswttiqbhrnfbueldwetbtrxqsbvzqcd"
        val ferh: String = "jfyhijsdhdxmiphkhqcctgzxjyjpglet"
        val jrqi: String = "tasnkbqoufymdyyiknxqfufgivfumdey"
        val vjvv: String = "yphfezoejmpwebwpyjsxtjysgxudafwc"
        val urhu: String = "mrhlldeihmygkwnyghmrdwqdhdzeyeoe"
        val dffg: String = "dlslngjjwuxydvzbhddccmfhjxxxyfya"
        val mvrc: String = "fsgymrkchdchpwxqkkxazdlmubbameei"
        val egxq: String = "nwrokxsjlpjdhswfqxhuaizksnmzixtn"
        val fcid: String = "tophqxcvgcvoulwniequipnprxlpylzg"
        val iwfc: String = "okwjrqlodgfsifizppxkeeltgrlngdmg"
        val epgp: String = "hijhtlpgfvjbdgdzhbljrtbrqnhaahpl"
        val ozcx: String = "yzxabkermiaiqcbfljwhpdzqmbxglpdl"
        val mpbg: String = "cmwnyiyrsbwgqqmcaniaojijtkanpfdc"
        val xcfl: String = "izxvlajysvzcoikqcwxjdsczdcoeactk"
        val ztgv: String = "snuvtqysyrhgewwuejalgbytumjkyfua"
        val vifu: String = "wuejbaohgjmrooxygturxsmzehpmfrcj"
        val bxsz: String = "evgbgxwnvbdeapruvwmnxlkckdmqvrqo"
        val kzjf: String = "sjcmazirqfndznvhpbyhxmylwduxaefl"
        val enrv: String = "ffsqhydlrvulgftvdsedbglwgsbptdzr"
        val cmdv: String = "xjnbjupbfuolvgthumkxhfmgxclugheo"
        val nhpw: String = "oggqrkjagfpoiydivjygrlqxjapyldqi"
        val jzmy: String = "oeevrvyewfuzdirjxasbiuvfzhxbegsr"
        val jnbs: String = "fhxaigytdhndozzezzexvelgzpsbmqss"
        val vdwr: String = "giywkallsmyfjlmxkmmirasdfotxyvgt"
        val mgie: String = "fbmzkwubykwpfhseqzdsjzdmyyruaitq"
        val higp: String = "xkhzheejubrjmurvsgzcighuolipodfi"
        val daal: String = "zunvzupbuejirmzlsotfgixlwnoigmeo"
        val heyy: String = "zdabcbvxcwbxxdyucyqtqkohistrsmfk"
        val xytm: String = "plnujvzgfaugieqmdqxdhlfsxsojruqm"
        val puyy: String = "icbkvirnzwslfjvrzkdevhnemmmxzuwy"
        val xvpf: String = "hdmpgvkkmhcuwpgqehpddwyghputbpsb"
        val gyjs: String = "pyzvlhbygasyoweoyxwfuvnzodwqkzym"
        val bigs: String = "xdbflsarscgcupsejbrmtdomqeiakety"
        val zzwt: String = "wjwowntjtblfdpmakzxvbdaebrgtbnyi"
        val wqnd: String = "knjjsviybtudlolfmtybojwfmfglbqyn"
        val tqkj: String = "xlqxeikunoxewcqxwbwnaksykffvnftl"
        val havu: String = "zonoqwktmfncvacqwtmhlmrglwgbmqrh"
        val dpxl: String = "jnwmdrugrmfduiftocwwghpichtrrrsl"
        val shfv: String = "rpxxwlxzruakqaclbnvmjaakikceijcl"
        val xgas: String = "ugdcocpcdjkrimfdxqskjgsubretpqvc"
        val nfcf: String = "ukocqknjfzlokjriubhgbfxtyczjfhoj"
        val szwo: String = "pmxhdfzfepnxiurquufssusdojpidkay"
        val wbbn: String = "hkrobuuzvtfcsttpeyhuobejobopbokg"
        val neqt: String = "uzotuqjnfqqlqrvkuamogakhwisrnchp"
        val dfuk: String = "dvzfnyothfhqaklaybdqnicliowululh"
        val tguy: String = "eckfdjoxvrqszqxqitoxvknyqajitwcd"
        val kxrv: String = "fypxnuvmkyemkdkzhqtwlesiuvuqgqti"
        val qgyh: String = "zmbaxrjxxdoheoasewisvlmjriztdjlq"
        val lvrw: String = "fbuqgsmyvgewosrwfwwddllxdoljqsbu"
        val kcjn: String = "puylagvzmgltbahspitjrlhgnixifxqm"
        val owdd: String = "yvpdythicagqnstjaszxkuausujpoyuf"
        val hxgu: String = "zjnitsroekrwpfhoprziihctfpubekyr"
        val sfcv: String = "htugcnvbhylccsjkggazqdnkfnrsvinb"
        val zyky: String = "ongmrbehlnizpphksedjsfzzgtsvtytz"
        val ydbb: String = "gntfglitjrpyvdkwyaeqluymcrubcsal"
        val wmsb: String = "pfggknxvdupmufwowoetcmnwyrfiuqlp"
        val wytz: String = "hdjheqpcraejofsnirqympoioprbxnzn"
        val lwdu: String = "wlpemeqdszuoqngmmyfhyjvojomuakgb"
        val tull: String = "vtajiipjzbeuetmpbnbobksfmwhgzsfw"
        val isjf: String = "luknvfocsqiartzzlmhxwebxhtvdswkr"
        val awfc: String = "geeruhpgwvrogrfdtlrfqexrarjgpeqd"
        val ptxb: String = "neeptlavcazkcodeiunvfbqerbshzoji"
        val nzit: String = "frfaiavktrvnyagjdtspqqggzjsnnbhz"
        val tjuf: String = "ubwdzavclzccdybweoehelnypmamygbp"
        val fgzg: String = "awpflqotnubbbofhlxhbhzygdufiregg"
        val jdkd: String = "fjdoucdsdgqybdobkpfevhsgivumavwi"
        val brfa: String = "miciqjrpukoesovslhkyqnodwcrqnrzc"
        val ofsr: String = "cgijkuiordhroarehlqfqcijymiavrxn"
        val fsei: String = "sigdhzsampbcplcrtzyxybybstytnugt"
        val pakq: String = "nzeqoewligpacgrnomrogybbikorwlhz"
        val mkhf: String = "oxuxsvuoovfegqoccudhidldtiugqfql"
        val vkty: String = "dwrrynrckwlqznqttogtllnipxsgxhlr"
        val sima: String = "hfndqjbicwuixknsjmmbresvdwewzdyb"
        val gcht: String = "jwzkateciiuzkkigwhwimqejjbgqywwq"
        val xgzb: String = "mkjrpaggqvvtrbsndzkwwnfpgjphhxac"
        val tvtw: String = "erculjgylbvfxfgibgbqabwqbqsmtkyt"
        val owou: String = "ysjpoyaqdtahcksltsbhjyuyxdvcakrm"
        val koya: String = "papqsinxcqlelklfhahmpsqyqaszmnua"
        val kqgd: String = "zyqrojvbrbuokrrdqalrpptyxtatmljq"
        val vixx: String = "wpqiwzhniltjztmpmhyxeqvgidhsqsli"
        val jljh: String = "pirwvhxlggklpxjsvxjkbltnnofpxldw"
        val nvcy: String = "scxrlcumjobcgojffdjbelkhjepfqxvj"
        val ogkf: String = "shhilprffalcqafeeqzvswfhygzdeasm"
        val pmhp: String = "fufnqqffdmdbmofxfdlnilqqnivqanaq"
        val smdy: String = "hbzbctefisnsnvudpnafunidolcbsvcr"
    }
    val map = LinkedHashMap<String, String>().also {
        it["ioqr"] = "wfnjuuzvtwpaiobztthgnusiezqebthi"
        it["ucpa"] = "fvvzuupgypdwhabsdibxnkenpgefkeon"
        it["zdxr"] = "ioqvkrrdrzdzxcteabhyaoejcvsckmsy"
        it["stmw"] = "okkuaaekibtmmjrprxltfzusbagyvtcd"
        it["mreb"] = "edavfspocapwrialvwnwcupwwcbiwlwt"
        it["objg"] = "guudtkspctpyiihzukinhifmhhxzokgu"
        it["muxx"] = "ecurtjsoiaobqxudvsethwzgbratwsis"
        it["ewzl"] = "ukxypolxoyndraiaxsatjtrtuznvurmb"
        it["mcyx"] = "ickiswtumkidcufofbrzqhjgqammnorn"
        it["foqi"] = "aqosuqpectvqfebxewvbzathwoltwkuj"
        it["ukak"] = "lgzlwiiyductkujorqbxztnggnjsslbz"
        it["slem"] = "dedcuygbwbywbskmshjhqdbssgqjzgbq"
        it["lrhj"] = "tcvcooeeorlkhhvqvqqmseatqbeygaeg"
        it["nwag"] = "mdlfzjlhqsxadqediseebxzaoiedbcfp"
        it["eftz"] = "ykeyrupitbjktqahaeaeziwxxbogpnuv"
        it["wwsc"] = "wktikamkuvasgxjqfhzddvqpmfciabey"
        it["zrex"] = "rxhbzomshcqiolltmbsuroquhmgamacw"
        it["maxb"] = "tubunywflprabuswbaxwqxmrdgqtvbwh"
        it["wiqy"] = "pkxzlutxzvshexadsuiopfzbhcwfqwiz"
        it["buhz"] = "ghawalybgitzetwvsgfzltweobxocged"
        it["zrlg"] = "zajxousbleadbnlbertocztlexvloxiu"
        it["yben"] = "udikcoefoseyjmpdzcqropltquousobt"
        it["jvis"] = "ezymshefayujluyhosuhnuzlnhvutcyw"
        it["gbsg"] = "xilzjkvkanrpbsnpmozqcmscuiifjyil"
        it["aeyv"] = "vpmomqciqzavrvfqmayvifnrycuwuhed"
        it["jrbt"] = "xbzvsfluotejwnqmlaovzldnvchlexnu"
        it["jrdn"] = "wfvnhxstpnyjvtlmxevofgziwdjcsdny"
        it["ddeh"] = "utsyiimeldbioxaauhztcdlblxvhyyfp"
        it["jljt"] = "wazlrafinmbxieapypltwmipcvqdgrjk"
        it["easb"] = "gwxbugljpjaeegynaqmqwpplxxnvzfhk"
        it["olna"] = "qesufdkzlocalhzhlkthymlhitggxhck"
        it["iqky"] = "vajtxhjkbjbrwupknijlcheoqqltftru"
        it["iwxi"] = "sdeqpqcqdzdjgkjujacoztsrkvwjkezb"
        it["fkan"] = "nxqlplzzwrttiwuaplohiucxsidfznnu"
        it["menh"] = "somabofuzswvfuvskbhafcllryvdzgjc"
        it["tyia"] = "qaayltmxtgwdvqjcfnrpohpwmqspczcb"
        it["fvdm"] = "azrsdachaejjhuxlaknthhvxqyaehsyu"
        it["zicj"] = "nevamciuhnjcxdepksggzjknoymudqjq"
        it["gxmb"] = "iuazruescaeedrqzlibyryizxrcnpmtm"
        it["emfu"] = "dzhjntpwyhlprkuibdxnimkwhryidbtc"
        it["vbub"] = "ybumflwygzxjmtwcrldanhgqpljjjpnt"
        it["yisg"] = "giyhtdilyneqnmjdlwawvkagllgefazu"
        it["rtnd"] = "xswttiqbhrnfbueldwetbtrxqsbvzqcd"
        it["ferh"] = "jfyhijsdhdxmiphkhqcctgzxjyjpglet"
        it["jrqi"] = "tasnkbqoufymdyyiknxqfufgivfumdey"
        it["vjvv"] = "yphfezoejmpwebwpyjsxtjysgxudafwc"
        it["urhu"] = "mrhlldeihmygkwnyghmrdwqdhdzeyeoe"
        it["dffg"] = "dlslngjjwuxydvzbhddccmfhjxxxyfya"
        it["mvrc"] = "fsgymrkchdchpwxqkkxazdlmubbameei"
        it["egxq"] = "nwrokxsjlpjdhswfqxhuaizksnmzixtn"
        it["fcid"] = "tophqxcvgcvoulwniequipnprxlpylzg"
        it["iwfc"] = "okwjrqlodgfsifizppxkeeltgrlngdmg"
        it["epgp"] = "hijhtlpgfvjbdgdzhbljrtbrqnhaahpl"
        it["ozcx"] = "yzxabkermiaiqcbfljwhpdzqmbxglpdl"
        it["mpbg"] = "cmwnyiyrsbwgqqmcaniaojijtkanpfdc"
        it["xcfl"] = "izxvlajysvzcoikqcwxjdsczdcoeactk"
        it["ztgv"] = "snuvtqysyrhgewwuejalgbytumjkyfua"
        it["vifu"] = "wuejbaohgjmrooxygturxsmzehpmfrcj"
        it["bxsz"] = "evgbgxwnvbdeapruvwmnxlkckdmqvrqo"
        it["kzjf"] = "sjcmazirqfndznvhpbyhxmylwduxaefl"
        it["enrv"] = "ffsqhydlrvulgftvdsedbglwgsbptdzr"
        it["cmdv"] = "xjnbjupbfuolvgthumkxhfmgxclugheo"
        it["nhpw"] = "oggqrkjagfpoiydivjygrlqxjapyldqi"
        it["jzmy"] = "oeevrvyewfuzdirjxasbiuvfzhxbegsr"
        it["jnbs"] = "fhxaigytdhndozzezzexvelgzpsbmqss"
        it["vdwr"] = "giywkallsmyfjlmxkmmirasdfotxyvgt"
        it["mgie"] = "fbmzkwubykwpfhseqzdsjzdmyyruaitq"
        it["higp"] = "xkhzheejubrjmurvsgzcighuolipodfi"
        it["daal"] = "zunvzupbuejirmzlsotfgixlwnoigmeo"
        it["heyy"] = "zdabcbvxcwbxxdyucyqtqkohistrsmfk"
        it["xytm"] = "plnujvzgfaugieqmdqxdhlfsxsojruqm"
        it["puyy"] = "icbkvirnzwslfjvrzkdevhnemmmxzuwy"
        it["xvpf"] = "hdmpgvkkmhcuwpgqehpddwyghputbpsb"
        it["gyjs"] = "pyzvlhbygasyoweoyxwfuvnzodwqkzym"
        it["bigs"] = "xdbflsarscgcupsejbrmtdomqeiakety"
        it["zzwt"] = "wjwowntjtblfdpmakzxvbdaebrgtbnyi"
        it["wqnd"] = "knjjsviybtudlolfmtybojwfmfglbqyn"
        it["tqkj"] = "xlqxeikunoxewcqxwbwnaksykffvnftl"
        it["havu"] = "zonoqwktmfncvacqwtmhlmrglwgbmqrh"
        it["dpxl"] = "jnwmdrugrmfduiftocwwghpichtrrrsl"
        it["shfv"] = "rpxxwlxzruakqaclbnvmjaakikceijcl"
        it["xgas"] = "ugdcocpcdjkrimfdxqskjgsubretpqvc"
        it["nfcf"] = "ukocqknjfzlokjriubhgbfxtyczjfhoj"
        it["szwo"] = "pmxhdfzfepnxiurquufssusdojpidkay"
        it["wbbn"] = "hkrobuuzvtfcsttpeyhuobejobopbokg"
        it["neqt"] = "uzotuqjnfqqlqrvkuamogakhwisrnchp"
        it["dfuk"] = "dvzfnyothfhqaklaybdqnicliowululh"
        it["tguy"] = "eckfdjoxvrqszqxqitoxvknyqajitwcd"
        it["kxrv"] = "fypxnuvmkyemkdkzhqtwlesiuvuqgqti"
        it["qgyh"] = "zmbaxrjxxdoheoasewisvlmjriztdjlq"
        it["lvrw"] = "fbuqgsmyvgewosrwfwwddllxdoljqsbu"
        it["kcjn"] = "puylagvzmgltbahspitjrlhgnixifxqm"
        it["owdd"] = "yvpdythicagqnstjaszxkuausujpoyuf"
        it["hxgu"] = "zjnitsroekrwpfhoprziihctfpubekyr"
        it["sfcv"] = "htugcnvbhylccsjkggazqdnkfnrsvinb"
        it["zyky"] = "ongmrbehlnizpphksedjsfzzgtsvtytz"
        it["ydbb"] = "gntfglitjrpyvdkwyaeqluymcrubcsal"
        it["wmsb"] = "pfggknxvdupmufwowoetcmnwyrfiuqlp"
        it["wytz"] = "hdjheqpcraejofsnirqympoioprbxnzn"
        it["lwdu"] = "wlpemeqdszuoqngmmyfhyjvojomuakgb"
        it["tull"] = "vtajiipjzbeuetmpbnbobksfmwhgzsfw"
        it["isjf"] = "luknvfocsqiartzzlmhxwebxhtvdswkr"
        it["awfc"] = "geeruhpgwvrogrfdtlrfqexrarjgpeqd"
        it["ptxb"] = "neeptlavcazkcodeiunvfbqerbshzoji"
        it["nzit"] = "frfaiavktrvnyagjdtspqqggzjsnnbhz"
        it["tjuf"] = "ubwdzavclzccdybweoehelnypmamygbp"
        it["fgzg"] = "awpflqotnubbbofhlxhbhzygdufiregg"
        it["jdkd"] = "fjdoucdsdgqybdobkpfevhsgivumavwi"
        it["brfa"] = "miciqjrpukoesovslhkyqnodwcrqnrzc"
        it["ofsr"] = "cgijkuiordhroarehlqfqcijymiavrxn"
        it["fsei"] = "sigdhzsampbcplcrtzyxybybstytnugt"
        it["pakq"] = "nzeqoewligpacgrnomrogybbikorwlhz"
        it["mkhf"] = "oxuxsvuoovfegqoccudhidldtiugqfql"
        it["vkty"] = "dwrrynrckwlqznqttogtllnipxsgxhlr"
        it["sima"] = "hfndqjbicwuixknsjmmbresvdwewzdyb"
        it["gcht"] = "jwzkateciiuzkkigwhwimqejjbgqywwq"
        it["xgzb"] = "mkjrpaggqvvtrbsndzkwwnfpgjphhxac"
        it["tvtw"] = "erculjgylbvfxfgibgbqabwqbqsmtkyt"
        it["owou"] = "ysjpoyaqdtahcksltsbhjyuyxdvcakrm"
        it["koya"] = "papqsinxcqlelklfhahmpsqyqaszmnua"
        it["kqgd"] = "zyqrojvbrbuokrrdqalrpptyxtatmljq"
        it["vixx"] = "wpqiwzhniltjztmpmhyxeqvgidhsqsli"
        it["jljh"] = "pirwvhxlggklpxjsvxjkbltnnofpxldw"
        it["nvcy"] = "scxrlcumjobcgojffdjbelkhjepfqxvj"
        it["ogkf"] = "shhilprffalcqafeeqzvswfhygzdeasm"
        it["pmhp"] = "fufnqqffdmdbmofxfdlnilqqnivqanaq"
        it["smdy"] = "hbzbctefisnsnvudpnafunidolcbsvcr"
    }
    println("Object vs Map (entryCount = 128, keySize = 4, valueSize = 32)")
    println("Object: ${any.getObjectGraphSize()}")
    println("Map: ${map.getObjectGraphSize()}")
}

